name: Build Docker Images

on:
  push:
    branches: [ "master" ]
    paths:
      - 'frontend/**'
      - 'backend/**'
  workflow_dispatch:  # Permite ejecución manual

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Frontend Image
        working-directory: ./frontend
        run: docker build -t miacrcrypto.azurecr.io/frontend:latest .

      - name: Build Backend Image
        working-directory: ./backend
        run: docker build -t miacrcrypto.azurecr.io/backend:latest .
