name: Build Docker Images

on:
  push:
    branches: [ "master" ]
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 1: Configurar QEMU (opcional, solo necesario para multi-arquitectura)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Paso 2: Configurar Buildx (para mejor soporte de builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Construir imagen del frontend
      - name: Build Frontend Image
        working-directory: ./frontend
        run: docker build -t miacrcrypto.azurecr.io/frontend:latest .

      # Paso 4: Construir imagen del backend
      - name: Build Backend Image
        working-directory: ./backend
        run: docker build -t miacrcrypto.azurecr.io/backend:latest .
